FROM python:3.12-slim-bookworm

WORKDIR /app
COPY requirements.txt requirements-stress.txt ./
RUN pip install --no-cache-dir -r requirements.txt -r requirements-stress.txt
COPY . .
CMD ["python", "stress_runner.py"]
