"""Ajout Text, Langue, Traduction

Revision ID: 0626af16fc43
Revises: 5502a29a3ab9
Create Date: 2024-05-12 17:15:55.549815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0626af16fc43'
down_revision = '5502a29a3ab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_language_code', ['code'])

    with op.batch_alter_table('text', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint('uq_text_key', ['key'])
        batch_op.create_unique_constraint(None, ['key'])
        batch_op.drop_column('created')
        batch_op.drop_column('text')

    with op.batch_alter_table('text_translation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'text', ['text_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'language', ['language_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_translation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'text', ['text_id'], ['id'])
        batch_op.create_foreign_key(None, 'language', ['language_id'], ['id'])

    with op.batch_alter_table('text', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('created', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint('uq_text_key', type_='unique')
        batch_op.drop_column('key')

    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.drop_constraint('uq_language_code', type_='unique')

    # ### end Alembic commands ###
