"""Ajout Table Css Variable Announce

Revision ID: 06dd14abcd07
Revises: 75932693183c
Create Date: 2024-11-01 17:13:40.722760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06dd14abcd07'
down_revision = '75932693183c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announce_css_variable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variable', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('announce_css_variable')
    # ### end Alembic commands ###
