"""Changement configVersion

Revision ID: 0868b3431cbc
Revises: 
Create Date: 2024-05-07 13:10:33.070426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0868b3431cbc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('button', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('label_en', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_present', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('shape', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('button', schema=None) as batch_op:
        batch_op.drop_column('shape')
        batch_op.drop_column('is_present')
        batch_op.drop_column('label_en')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
