"""Translation > Ajout key_name

Revision ID: 09acd8dc82d8
Revises: 529f2e885fb5
Create Date: 2024-09-02 12:22:39.806832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09acd8dc82d8'
down_revision = '529f2e885fb5'
branch_labels = None
depends_on = None


# Ajouter cette fonction de vérification
def column_exists(engine, table_name, column_name):
    insp = sa.inspect(engine)
    columns = [col['name'] for col in insp.get_columns(table_name)]
    return column_name in columns

def upgrade():
    # Vérifier si la colonne 'key_name' existe avant de tenter de l'ajouter
    bind = op.get_bind()
    if not column_exists(bind, 'translation', 'key_name'):
        with op.batch_alter_table('translation', schema=None) as batch_op:
            batch_op.add_column(sa.Column('key_name', sa.String(length=50)))
    else:
        print("Column 'key_name' already exists, skipping add column.")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translation', schema=None) as batch_op:
        batch_op.drop_column('key_name')

    # ### end Alembic commands ###
