"""Translation > Ajout key_name

Revision ID: 09acd8dc82d8
Revises: 529f2e885fb5
Create Date: 2024-09-02 12:22:39.806832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09acd8dc82d8'
down_revision = '529f2e885fb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translation', schema=None) as batch_op:
        batch_op.drop_column('key_name')

    # ### end Alembic commands ###
