"""Language > flag

Revision ID: 1314b5de23d2
Revises: da20e0267231
Create Date: 2024-09-02 15:25:47.910908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1314b5de23d2'
down_revision = 'da20e0267231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag_url', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.drop_column('flag_url')

    # ### end Alembic commands ###
