"""Added counter_id to Patient

Revision ID: 1a63c5961ec5
Revises: 246992f0285e
Create Date: 2024-05-09 14:12:53.409446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a63c5961ec5'
down_revision = '246992f0285e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('counter_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_patient_counter_id', 'counter', ['counter_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint('fk_patient_counter_id', type_='foreignkey')
        batch_op.drop_column('counter_id')

    # ### end Alembic commands ###
