"""Activity > Notification

Revision ID: 1fa2266b0e1f
Revises: 8fa48c59ff8a
Create Date: 2024-06-10 08:33:01.956567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fa2266b0e1f'
down_revision = '8fa48c59ff8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_column('notification')

    # ### end Alembic commands ###
