"""relation simple entre bouton et activité

Revision ID: 246992f0285e
Revises: 2899d06732f0
Create Date: 2024-05-08 16:24:27.636329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246992f0285e'
down_revision = '2899d06732f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buttons_activities')
    with op.batch_alter_table('button', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_button_activity_id', 'activity', ['activity_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('button', schema=None) as batch_op:
        batch_op.drop_constraint('fk_button_activity_id', type_='foreignkey')
        batch_op.drop_column('activity_id')

    op.create_table('buttons_activities',
    sa.Column('button_id', sa.INTEGER(), nullable=False),
    sa.Column('activity_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name='fk_buttons_activities_activity_id'),
    sa.ForeignKeyConstraint(['button_id'], ['button.id'], name='fk_buttons_activities_button_id'),
    sa.PrimaryKeyConstraint('button_id', 'activity_id')
    )
    # ### end Alembic commands ###
