"""Role > announce, patient, gallery

Revision ID: 275b56c64388
Revises: 071b95b5d94b
Create Date: 2024-12-25 17:20:35.382194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275b56c64388'
down_revision = '071b95b5d94b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_announce', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('admin_patient', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('admin_gallery', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('admin_gallery')
        batch_op.drop_column('admin_patient')
        batch_op.drop_column('admin_announce')

    # ### end Alembic commands ###
