"""Language > ajout des infos pour les voix

Revision ID: 288835dc3e94
Revises: 34c7802433f6
Create Date: 2024-09-28 10:20:12.668431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288835dc3e94'
down_revision = '34c7802433f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voice_model', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('voice_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.drop_column('voice_name')
        batch_op.drop_column('voice_model')

    # ### end Alembic commands ###
