"""bouton text color

Revision ID: 2899d06732f0
Revises: 
Create Date: 2024-05-08 15:16:39.244068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2899d06732f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('button', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('button', schema=None) as batch_op:
        batch_op.drop_column('text_color')

    # ### end Alembic commands ###
