"""Language > Ajout region pour Google

Revision ID: 2b5bfc00161c
Revises: 98399efeb252
Create Date: 2024-09-28 16:52:03.456023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b5bfc00161c'
down_revision = '98399efeb252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voice_google_region', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.drop_column('voice_google_region')

    # ### end Alembic commands ###
