"""Activity > staff_id

Revision ID: 2b7255f3a5d3
Revises: f0e8445b92cf
Create Date: 2024-06-22 11:40:42.029406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b7255f3a5d3'
down_revision = 'f0e8445b92cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_activity_staff_id', 'pharmacist', ['staff_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint('fk_activity_staff_id', type_='foreignkey')
        batch_op.drop_column('staff_id')

    # ### end Alembic commands ###
