"""Interface > + value

Revision ID: 324f83a1ce98
Revises: 768525d9a8b8
Create Date: 2024-09-03 13:20:05.108310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324f83a1ce98'
down_revision = '768525d9a8b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_value', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text', schema=None) as batch_op:
        batch_op.drop_column('text_value')

    # ### end Alembic commands ###
