"""Language pour Patient > nullable 

Revision ID: 34c7802433f6
Revises: c4f5c1c2f4df
Create Date: 2024-09-28 08:53:00.989894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34c7802433f6'
down_revision = 'c4f5c1c2f4df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('language_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('language_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
