"""Ajout Json dans ConfigOption

Revision ID: 40c1b6b369a8
Revises: 324f83a1ce98
Create Date: 2024-09-21 16:42:53.830476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40c1b6b369a8'
down_revision = '324f83a1ce98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config_option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config_option', schema=None) as batch_op:
        batch_op.drop_column('value_json')

    # ### end Alembic commands ###
