"""Language > Ajout voice_is_active

Revision ID: 44fbea5dd5cd
Revises: 2b5bfc00161c
Create Date: 2024-09-28 18:20:58.248598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44fbea5dd5cd'
down_revision = '2b5bfc00161c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voice_is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.drop_column('voice_is_active')

    # ### end Alembic commands ###
