"""Add 2 timestamps

Revision ID: 515b09694539
Revises: cbc4584745fe
Create Date: 2024-09-30 15:13:46.591668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '515b09694539'
down_revision = 'cbc4584745fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp_counter', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('timestamp_end', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('timestamp_end')
        batch_op.drop_column('timestamp_counter')

    # ### end Alembic commands ###
