"""Added is_parent to Button

Revision ID: 5502a29a3ab9
Revises: ed8c846a472e
Create Date: 2024-05-12 09:17:36.470803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5502a29a3ab9'
down_revision = 'ed8c846a472e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('button', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_parent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('button', schema=None) as batch_op:
        batch_op.drop_column('is_parent')

    # ### end Alembic commands ###
