"""Button > image url

Revision ID: 6beabd9b6834
Revises: d86772e79094
Create Date: 2024-05-08 10:32:49.195101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6beabd9b6834'
down_revision = 'd86772e79094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buttons_activities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buttons_activities',
    sa.Column('counter_id', sa.INTEGER(), nullable=False),
    sa.Column('activity_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['counter_id'], ['counter.id'], ),
    sa.PrimaryKeyConstraint('counter_id', 'activity_id')
    )
    # ### end Alembic commands ###
