"""Counter > ajout auto_calling

Revision ID: 7067c7547c07
Revises: 0740b51e0a43
Create Date: 2024-08-07 07:26:55.690167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7067c7547c07'
down_revision = '0740b51e0a43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('counter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_calling', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('counter', schema=None) as batch_op:
        batch_op.drop_column('auto_calling')

    # ### end Alembic commands ###
