"""Language > sort_order

Revision ID: 768525d9a8b8
Revises: 1314b5de23d2
Create Date: 2024-09-02 18:07:08.337510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768525d9a8b8'
down_revision = '1314b5de23d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.drop_column('sort_order')

    # ### end Alembic commands ###
