"""Role > staff

Revision ID: 77bb4e949839
Revises: 2e114b50bf28
Create Date: 2024-12-25 17:15:05.287030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77bb4e949839'
down_revision = '2e114b50bf28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_staff', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('admin_staff')

    # ### end Alembic commands ###
