"""Language > ajout nom google voice

Revision ID: 98399efeb252
Revises: cfdcc792e1c0
Create Date: 2024-09-28 10:58:47.438070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98399efeb252'
down_revision = 'cfdcc792e1c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voice_google_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.drop_column('voice_google_name')

    # ### end Alembic commands ###
