"""Role > music play + option 

Revision ID: abc04012148c
Revises: 275b56c64388
Create Date: 2024-12-25 17:29:34.900811

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'abc04012148c'
down_revision = '275b56c64388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_music_play', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('admin_music_options', sa.String(length=10), nullable=False))
        batch_op.drop_column('admin_dashboard')
        batch_op.drop_column('admin_music')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_music', mysql.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('admin_dashboard', mysql.VARCHAR(length=10), nullable=False))
        batch_op.drop_column('admin_music_options')
        batch_op.drop_column('admin_music_play')

    # ### end Alembic commands ###
