"""Activity > specific message

Revision ID: bd32931a1806
Revises: f7f7f40d9103
Create Date: 2024-08-24 07:07:58.190709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd32931a1806'
down_revision = 'f7f7f40d9103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_specific_message', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_column('activity_specific_message')

    # ### end Alembic commands ###
