"""Ajout Language pour Patient

Revision ID: c4f5c1c2f4df
Revises: 40c1b6b369a8
Create Date: 2024-09-28 08:34:49.373479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4f5c1c2f4df'
down_revision = '40c1b6b369a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_patient_language_id', 'language', ['language_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint('fk_patient_language_id', type_='foreignkey')
        batch_op.drop_column('language_id')

    # ### end Alembic commands ###
