"""Initial migration after clearing alembic_version

Revision ID: cbc4584745fe
Revises: 
Create Date: 2024-09-30 15:08:19.524194

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cbc4584745fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.drop_column('_status')
        batch_op.drop_column('timestamp_end')
        batch_op.drop_column('timestamp_counter')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp_counter', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('timestamp_end', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('_status', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
