"""Language > ajout nom gtts voice

Revision ID: cfdcc792e1c0
Revises: 288835dc3e94
Create Date: 2024-09-28 10:57:42.205563

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cfdcc792e1c0'
down_revision = '288835dc3e94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voice_gtts_name', sa.String(length=100), nullable=True))
        batch_op.drop_column('voice_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voice_name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('voice_gtts_name')

    # ### end Alembic commands ###
