"""Ajout nom pour activityschedule 

Revision ID: d7c415fab06b
Revises: 
Create Date: 2024-05-27 14:21:47.814463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7c415fab06b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_schedules', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
