"""Changement configVersion

Revision ID: d86772e79094
Revises: 0868b3431cbc
Create Date: 2024-05-08 08:44:12.980413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd86772e79094'
down_revision = '0868b3431cbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('button')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('button',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('label', sa.VARCHAR(length=50), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('parent_button_id', sa.INTEGER(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('label_en', sa.VARCHAR(length=50), nullable=True),
    sa.Column('is_present', sa.BOOLEAN(), nullable=True),
    sa.Column('shape', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['parent_button_id'], ['button.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
