"""ManytoMany Activity -> Counters

Revision ID: db7c652f6a6e
Revises: 
Create Date: 2024-05-06 15:11:52.744542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db7c652f6a6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('counters_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('counter_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'counter', ['counter_id'], ['id'])
        batch_op.drop_column('pharmacist_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('counters_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacist_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'pharmacist', ['pharmacist_id'], ['id'])
        batch_op.drop_column('counter_id')

    # ### end Alembic commands ###
