"""Added staff to Counter

Revision ID: ed8c846a472e
Revises: a25619ef67e9
Create Date: 2024-05-11 14:14:46.602961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed8c846a472e'
down_revision = 'a25619ef67e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('counter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_counter_staff_id', 'pharmacist', ['staff_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('counter', schema=None) as batch_op:
        batch_op.drop_constraint('fk_counter_staff_id', type_='foreignkey')
        batch_op.drop_column('staff_id')

    # ### end Alembic commands ###
