"""enlever default à Pharmacist

Revision ID: f7f7f40d9103
Revises: 
Create Date: 2024-08-18 18:04:34.092534

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7f7f40d9103'
down_revision = None
branch_labels = None
depends_on = None


# Ajouter cette fonction de vérification
def column_exists(engine, table_name, column_name):
    insp = sa.inspect(engine)
    columns = [col['name'] for col in insp.get_columns(table_name)]
    return column_name in columns

def upgrade():
    # Vérifier si la colonne 'default' existe avant de tenter de la supprimer
    bind = op.get_bind()
    if column_exists(bind, 'pharmacist', 'default'):
        with op.batch_alter_table('pharmacist', schema=None) as batch_op:
            batch_op.drop_column('default')
    else:
        print("Column 'default' does not exist, skipping drop column.")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pharmacist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
