"""Role > security split (view/manage/grant)

Revision ID: g4h5i6j7k8l9
Revises: e9f0a1b2c3d4
Create Date: 2026-02-11 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'g4h5i6j7k8l9'
down_revision = 'e9f0a1b2c3d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_security_view', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('admin_security_manage', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('admin_security_grant', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('admin_security_grant')
        batch_op.drop_column('admin_security_manage')
        batch_op.drop_column('admin_security_view')

    # ### end Alembic commands ###
